// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quanlysach.Models;

#nullable disable

namespace Quanlysach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quanlysach.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Khanh",
                            CategoryId = 1,
                            Description = "Học ASP.NET Core",
                            Image = "book1.jpg",
                            Price = 100m,
                            Title = "ASP.NET Core MVC"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Tong",
                            CategoryId = 2,
                            Description = "Lập trình C# nâng cao",
                            Image = "book2.jpg",
                            Price = 200m,
                            Title = "C# Advanced"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Bao Khanh",
                            CategoryId = 3,
                            Description = "Kinh doanh hiện đại",
                            Image = "book3.jpg",
                            Price = 150m,
                            Title = "Startup 2026"
                        });
                });

            modelBuilder.Entity("Quanlysach.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Công nghệ"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Lập trình"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Kinh doanh"
                        });
                });

            modelBuilder.Entity("Quanlysach.Models.Book", b =>
                {
                    b.HasOne("Quanlysach.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Quanlysach.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
